[project]
name = "ZenithNode"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.zenith-node]
path = "contracts/zenith-node.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
